apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: serviceb
resources:
  - namespace.yaml
  - kubernetes-deployment.yaml
  #Apply istio config
  - istio.yaml
  - tls.yml
commonLabels:
  version: v2


