#create kustomize script
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - kubernetes-deployment.yml
commonLabels:
  version: v1
images:
  - name: servicea
    newName: myrgmyacr.azurecr.io/servicea
    
   
