#kubernetes deployment for serviceav2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceav2
  labels:
    app: servicea
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
        version: v2
    spec:
      containers:
        - name: serviceav2
          image: myrgmyacr.azurecr.io/servicea
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GPTKEY
              valueFrom:
                configMapKeyRef:
                  name: chatgpt-config
                  key: key
          #populate env from configmap
          envFrom:
              - configMapRef:
                  name: serviceav2-config
          resources:
            requests:
              cpu: 100m
              memory: 24Mi
            limits:
              cpu: 100m
              memory: 24Mi
---
#configmap for serviceav2
apiVersion: v1
kind: ConfigMap
metadata:
  name: serviceav2-config
data:
  DOWNSTREAM_URL: "http://serviceav2/health"
---




