#kubernetes deployment for servicea
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  labels:
    app: servicea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
        - name: servicea
          image: myrgmyacr.azurecr.io/servicea
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          #populate env from configmap
          envFrom:
              - configMapRef:
                  name: servicea-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
#configmap for servicea
apiVersion: v1
kind: ConfigMap
metadata:
  name: servicea-config
data:
  DOWNSTREAM_URL: "http://serviceb.serviceb.svc.cluster.local/message"




