apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: myapp
  serviceName: myservice
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      deletePolicy: RemoveOnStatefulSetDeletion
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
